version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00" # UTC
    labels:
      - "domain: deps"
    commit-message:
      prefix: "robo(deps)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "domain: ci"
    commit-message:
      prefix: "robo(ci)"
