name: Bloat

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Rustup setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo bloat
        uses: orf/cargo-bloat-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
