name: Build and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
          rustup component add rustfmt
          cargo fmt -- --check || (echo "Please reformat your code with 'cargo
          fmt' (version $(cargo fmt --version))"; false)

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
    - uses: actions/checkout@v2

    - name: Rustup setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{ matrix.target }}

    - name: Unit tests
      run: |
          cargo test --target ${{ matrix.target }}

  build:
    needs: [lint, tests]

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu]

    steps:
    - uses: actions/checkout@v2

    - name: Rustup setup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{ matrix.target }}

    - name: Check
      run: |
          cargo check --target ${{ matrix.target }}

    - name: Build
      run: |
          cargo build --target ${{ matrix.target }}
