name: Build and test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
          rustup component add rustfmt
          cargo fmt -- --check || (echo "Please reformat your code with 'cargo
          fmt' (version $(cargo fmt --version))"; false)

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      run: |
          cargo test

  build:
    runs-on: ubuntu-latest
    needs: [lint, tests]

    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: |
          cargo check
    - name: Build
      run: |
          cargo build
