name: code-coverage

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run tarpaulin
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --engine llvm --out Xml -- --test-threads 1

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml
